### PR TITLE
Fix ##253 - Update to Openssl 1.1.1l for tor client

### LINKED ISSUE #253: Update to Openssl 1.1.1l for tor client
https://www.openssl.org/news/openssl-1.1.1-notes.html

### PR DESCRIPTION
**Pull request by jumde**
fix #253

### CODE REVIEW

**Review by bbondy — APPROVED** [review]

File: scripts/packageTorClient.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ const downloadTorClient = (platform) => {
   const torS3Prefix = process.env.S3_DEMO_TOR_PREFIX
 
   const torVersion = '0.4.5.10'
```
Comment (emerick) [inline scripts/packageTorClient.js:22]: No need to update this version number?

Comment (jumde) [reply scripts/packageTorClient.js:22]: We are just updating the OpenSSL library, tor version remains the same. Updated the `braveVersion` here: https://github.com/brave/brave-core-crx-packager/pull/254/files#diff-50089866665384155d804130c89c80a81693797ea034d0786391b720c16a9c7dR23

**Review by emerick — APPROVED** [review]
